export const rooms = [
  {
    id: "budget-family-room",
    slug: "budget-family-room",
    roomNumber: "203",
    availablePhysicalRooms: ["203", "303"],
    name: "Budget Family Room",
    type: "Budget Family Room",
    guests: 4,
    occupancy: "3 Adults, 1 Child",
    size: "224 Sq. Ft.",
    beds: "1 King Bed + 1 Single Bed",
    bedDetails: {
      king: "1 King Size Bed",
      single: "1 Single Bed",
    },
    features: ["Budget Friendly", "En-suite Bathroom", "High-Speed Wi-Fi"],
    description:
      "A comfortable, budget-friendly family room designed for families, small groups, or trekkers resting before and after Himalayan trails. Features one King size bed and one Single bed, accommodating up to 3 adults and 1 child. Includes private attached bathroom with 24/7 hot water, bright natural light, clean linen, and shared self-kitchen privileges.",
    amenities: [
      "High-speed Fiber Wi-Fi",
      "1 King Bed + 1 Single Bed",
      "Private Attached Bathroom (24/7 Hot Water)",
      "Ceiling Fan / Heating",
      "Shared Guest Kitchen Access",
      "Complimentary Trekker Luggage Storage",
      "Daily Housekeeping",
      "24/7 Front Desk Assistance",
    ],
    price: 20,
    currency: "USD",
    priceNprApprox: 2700,
    status: "AVAILABLE",
    image: [
      "/triple.webp",
      "/changes_photo/doubleBedRoom.webp",
      "/changes_photo/washRoom.webp",
      "/changes_photo/balkani.webp",
    ],
  },
  {
    id: "deluxe-room",
    slug: "deluxe-room",
    roomNumber: "201",
    availablePhysicalRooms: ["201", "202"],
    name: "Deluxe Room",
    type: "Deluxe Room",
    guests: 3,
    occupancy: "2 Adults, 1 Child",
    size: "168 Sq. Ft.",
    beds: "1 King Bed",
    bedDetails: {
      king: "1 King Size Bed",
    },
    features: ["Air Conditioned (AC)", "Work Desk", "Quiet Rest"],
    description:
      "A serene and comfortable deluxe room featuring a restful King size bed accommodating up to 2 adults and 1 child. Perfect for couples, solo travelers, or digital nomads seeking quiet, peaceful sleep in the heart of Thamel. Equipped with individual climate control (air conditioning), private modern ensuite bathroom with 24/7 hot shower, work desk, and shared guest kitchen access.",
    amenities: [
      "Air Conditioning (AC)",
      "High-speed Fiber Wi-Fi",
      "1 King Size Bed",
      "Private Ensuite Bathroom (24/7 Hot Water)",
      "Work Desk & Seating",
      "Shared Guest Kitchen Access",
      "Complimentary Trekker Luggage Storage",
      "Daily Housekeeping",
    ],
    price: 20,
    currency: "USD",
    priceNprApprox: 2700,
    status: "AVAILABLE",
    image: [
      "/changes_photo/deluxeRoom_ai.webp",
      "/changes_photo/washRoom.webp",
      "/changes_photo/balkani.webp",
      "/changes_photo/viewSeen.webp",
    ],
  },
  {
    id: "family-room",
    slug: "family-room",
    roomNumber: "301",
    availablePhysicalRooms: ["301", "302"],
    name: "Family Room",
    type: "Family Room",
    guests: 4,
    occupancy: "3 Adults, 1 Child",
    size: "224 Sq. Ft.",
    beds: "1 King Bed + 1 Single Bed",
    bedDetails: {
      king: "1 King Size Bed",
      single: "1 Single Bed",
    },
    features: ["Air Conditioned (AC)", "Spacious Layout", "Family Friendly"],
    description:
      "Spacious and peaceful family accommodation designed for 3 adults and 1 child. Equipped with air conditioning (AC), one King size bed and one Single bed with comfortable mattresses, ample space for luggage, private attached bathroom with continuous hot water shower, and access to our shared self-kitchen.",
    amenities: [
      "Air Conditioning (AC)",
      "High-speed Fiber Wi-Fi",
      "1 King Bed + 1 Single Bed",
      "Private Attached Bathroom (24/7 Hot Water)",
      "Comfortable Seating Area",
      "Shared Guest Kitchen Access",
      "Complimentary Trekker Luggage Storage",
      "Daily Housekeeping",
    ],
    price: 30,
    currency: "USD",
    priceNprApprox: 4000,
    status: "AVAILABLE",
    image: [
      "/changes_photo/doubleBed.webp",
      "/changes_photo/washRoom.webp",
      "/changes_photo/balkani.webp",
      "/changes_photo/viewSeen.webp",
    ],
  },
];
