export const rooms = [
  {
    id: 201,
    roomNumber: "201",
    name: "Standard Double Room",
    type: "Standard Double",
    guests: 2,
    size: "260 Sq. Ft.",
    beds: "1 Queen Bed",
    features: ["Shared Kitchen Access", "High-speed Wi-Fi"],
    description:
      "A serene and comfortable double room located on the 2nd floor, featuring an orthopedic queen bed, bright natural light, soundproof windows, and direct access to our shared rooftop kitchen. Perfect for couples or solo travelers exploring Thamel.",
    amenities: [
      "High-speed Wi-Fi",
      "Private Ensuite Bathroom",
      "24/7 Hot Water",
      "Work Desk & Chair",
      "Shared Kitchen Access",
      "Luggage Storage",
    ],
    price: 3500,
    currency: "NPR",
    status: "AVAILABLE",
    image: [
      "/room1/room.webp",
      "/room1/room2.webp",
      "/room2/DSC00132.webp",
    ],
  },
  {
    id: 203,
    roomNumber: "203",
    name: "Deluxe Twin Room",
    type: "Deluxe Twin",
    guests: 2,
    size: "300 Sq. Ft.",
    beds: "2 Single Beds",
    features: ["Connecting Balcony View", "Work Friendly"],
    description:
      "The Deluxe Twin Room is an ideal setup for trekking partners, colleagues, or friends. Features two separate comfortable single beds, ergonomic workspace, and quick elevator access to the dining and rooftop areas.",
    amenities: [
      "High-speed Wi-Fi",
      "2 Single Beds",
      "Private Bathroom & Shower",
      "Work Desk",
      "Shared Kitchen Access",
      "Daily Housekeeping",
    ],
    price: 4200,
    currency: "NPR",
    status: "AVAILABLE",
    image: [
      "/room3/DSC00136.webp",
      "/room3/DSC00137.webp",
      "/room3/DSC00138.webp",
    ],
  },
  {
    id: 301,
    roomNumber: "301",
    name: "Deluxe Double Room",
    type: "Deluxe Double",
    guests: 2,
    size: "350 Sq. Ft.",
    beds: "1 King Bed",
    features: ["Mountain / City Glimpse", "Extra Spacious"],
    description:
      "Our comfortable Deluxe Double Room on the 3rd floor offers warm Sherpa hospitality, a restful king-sized bed, seating corner, and serene atmosphere after a busy day in Kathmandu.",
    amenities: [
      "High-speed Wi-Fi",
      "King Size Bed",
      "Private Attached Bathroom (24/7 Hot Water)",
      "Flat-screen TV",
      "Tea/Coffee Maker",
      "Shared Kitchen Access",
    ],
    price: 4500,
    currency: "NPR",
    status: "AVAILABLE",
    image: [
      "/room4/DSC00140.webp",
      "/room4/DSC00141.webp",
      "/room4/DSC00142.webp",
    ],
  },
  {
    id: 302,
    roomNumber: "302",
    name: "Standard Twin Room",
    type: "Standard Twin",
    guests: 2,
    size: "280 Sq. Ft.",
    beds: "2 Single Beds",
    features: ["Quiet Courtyard Side", "Fast Wi-Fi"],
    description:
      "Comfortable and peaceful twin bedroom facing the quiet side of the property. Great for resting before and after Himalayan treks, equipped with warm duvets and private hot shower.",
    amenities: [
      "High-speed Wi-Fi",
      "2 Single Beds",
      "Ensuite Hot Shower",
      "Power Sockets at Bedside",
      "Shared Kitchen Access",
    ],
    price: 3800,
    currency: "NPR",
    status: "AVAILABLE",
    image: [
      "/room2/DSC00133.webp",
      "/room2/DSC00134.webp",
      "/room2/DSC00135.webp",
    ],
  },
  {
    id: 303,
    roomNumber: "303",
    name: "Family Suite",
    type: "Family Suite",
    guests: 4,
    size: "480 Sq. Ft.",
    beds: "1 King + 2 Singles",
    features: ["Family Friendly", "Connecting Layout", "Rooftop Access"],
    description:
      "Spacious family suite designed for groups and families. Features one king bed and two single beds, ample luggage space, and immediate proximity to the rooftop kitchen and lounge.",
    amenities: [
      "High-speed Wi-Fi",
      "Spacious Family Living",
      "King Bed + 2 Single Beds",
      "Large Bathroom",
      "Shared Kitchen Access",
      "Laundry Service Available",
    ],
    price: 6500,
    currency: "NPR",
    status: "AVAILABLE",
    image: [
      "/room4/DSC00145.webp",
      "/room4/DSC00146.webp",
      "/room4/DSC00153.webp",
    ],
  },
];
