export const rooms = [
  {
    id: 101,
    roomNumber: "101",
    name: "Budget Family Room",
    type: "Budget Family Room",
    guests: 4,
    occupancy: "3 Adults, 1 Child",
    size: "320 Sq. Ft.",
    beds: "1 King Bed (32.5 sq. ft) + 1 Single Bed (19.5 sq. ft)",
    bedDetails: {
      king: "1 King Size Bed (32.5 sq. ft)",
      single: "1 Single Bed (19.5 sq. ft)",
    },
    features: ["Budget Friendly", "Shared Kitchen Access", "High-speed Wi-Fi"],
    description:
      "A comfortable, budget-friendly family room designed for small families or trekking groups visiting Kathmandu. Features one King size bed (32.5 sq. ft) and one Single bed (19.5 sq. ft), comfortably accommodating up to 3 adults and 1 child. Includes private attached bathroom with 24/7 hot water, bright natural light, and access to our shared self-kitchen.",
    amenities: [
      "High-speed Wi-Fi",
      "1 King Bed (32.5 sq. ft)",
      "1 Single Bed (19.5 sq. ft)",
      "Private Attached Bathroom (24/7 Hot Water)",
      "Air Conditioning",
      "Shared Kitchen Access",
      "Luggage Storage",
      "Daily Housekeeping",
    ],
    price: 20,
    currency: "USD",
    priceNprApprox: 2700,
    status: "AVAILABLE",
    image: [
      "/changes_photo/doubleBedRoom.jpeg",
      "/changes_photo/doubleBed.jpeg",
      "/room1/room.webp",
      "/room1/room2.webp",
    ],
  },
  {
    id: 201,
    roomNumber: "201",
    name: "Deluxe Room",
    type: "Deluxe Room",
    guests: 3,
    occupancy: "2 Adults, 1 Child",
    size: "280 Sq. Ft.",
    beds: "1 King Bed (32.5 sq. ft)",
    bedDetails: {
      king: "1 King Size Bed (32.5 sq. ft)",
    },
    features: ["Bright Daylight", "Work Friendly", "Quiet Rest"],
    description:
      "A serene and comfortable deluxe room featuring a restful King size bed (32.5 sq. ft) accommodating up to 2 adults and 1 child. Perfect for couples or travelers seeking quiet, peaceful sleep in the heart of Thamel. Equipped with air conditioning, private ensuite bathroom with continuous hot water, work desk, and full access to our shared self-kitchen.",
    amenities: [
      "High-speed Wi-Fi",
      "1 King Size Bed (32.5 sq. ft)",
      "Private Ensuite Bathroom (24/7 Hot Water)",
      "Air Conditioning",
      "Work Desk & Chair",
      "Shared Kitchen Access",
      "Luggage Storage",
      "Daily Housekeeping",
    ],
    price: 20,
    currency: "USD",
    priceNprApprox: 2700,
    status: "AVAILABLE",
    image: [
      "/changes_photo/singleBedWithSofa.jpeg",
      "/room4/DSC00140.webp",
      "/room4/DSC00141.webp",
      "/room4/DSC00142.webp",
    ],
  },
  {
    id: 301,
    roomNumber: "301",
    name: "Family Room",
    type: "Family Room",
    guests: 4,
    occupancy: "3 Adults, 1 Child",
    size: "380 Sq. Ft.",
    beds: "1 King Bed (32.5 sq. ft) + 1 Single Bed (19.5 sq. ft)",
    bedDetails: {
      king: "1 King Size Bed (32.5 sq. ft)",
      single: "1 Single Bed (19.5 sq. ft)",
    },
    features: ["Extra Spacious", "Family Friendly", "Shared Kitchen Access"],
    description:
      "Spacious and peaceful family accommodation designed for 3 adults and 1 child. Equipped with one King size bed (32.5 sq. ft) and one Single bed (19.5 sq. ft) with supportive mattresses, ample space for luggage, private attached bathroom with continuous hot water, and direct proximity to the shared rooftop self-use kitchen.",
    amenities: [
      "High-speed Wi-Fi",
      "1 King Size Bed (32.5 sq. ft)",
      "1 Single Bed (19.5 sq. ft)",
      "Private Attached Bathroom (24/7 Hot Water)",
      "Air Conditioning",
      "Seating Corner",
      "Shared Kitchen Access",
      "Luggage Storage",
      "Daily Housekeeping",
    ],
    price: 30,
    currency: "USD",
    priceNprApprox: 4000,
    status: "AVAILABLE",
    image: [
      "/changes_photo/doubleBed.jpeg",
      "/room4/DSC00145.webp",
      "/room4/DSC00146.webp",
      "/room4/DSC00153.webp",
    ],
  },
];
